### ISSUE TITLE
http://dxr.mozilla.org/ cross-domain request support

### ISSUE THREAD

**Issue by chinhodado** [mozilla/dxr#527] opened 2016-04-21 00:45 UTC
Not sure if this is the place to ask, but I've been trying to make ajax requests to http://dxr.mozilla.org/ and unable to do so because the server doesn't response with the `Access-Control-Allow-Origin` header set. 

Is there any way I can make a cross-domain request to http://dxr.mozilla.org/ ?

**Comment by kleintom** [comment] 2016-04-22 15:37
I think some version of this is being discussed, but not yet available - compare
https://wiki.mozilla.org/DXR_Roadmap#UI.2FUX (the part about exposing "a well-documented public API")
and the open bug https://bugzilla.mozilla.org/show_bug.cgi?id=1193347

Erik may be able to give a clearer picture of where things stand when he returns.

**Comment by KWierso** [comment] 2017-04-09 02:58
Any chance this could get looked at?

**Comment by erikrose** [comment] 2017-04-10 20:25
Dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1354787, which we're fixing.

**Closed by erikrose** 2017-04-10 20:25 UTC
